apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-redis-aggregator
  namespace: gpu-mig-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-redis-aggregator
  template:
    metadata:
      labels:
        app: gpu-redis-aggregator
    spec:
      serviceAccountName: gpu-redis-aggregator

      # 如果你的 ghcr 镜像仓库是私有的，取消下面两行注释
      # imagePullSecrets:
      #   - name: ghcr-creds

      containers:
        - name: gpu-redis-aggregator
          image: ghcr.io/lsjzxf/gpu-redis-aggregator/gpu-redis-aggregator:sha-c2e216d
          imagePullPolicy: IfNotPresent

          env:
            - name: REDIS_ADDR
              value: "redis.gpu-insight-cache.svc.cluster.local:6379"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_PREFIX
              value: "gpuinsight:v1"
            - name: CACHE_TTL
              value: "30s"

          ports:
            - name: http
              containerPort: 8080

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10